### ISSUE TITLE
Log incoming http requests on TPS

### ISSUE THREAD

**Issue by vvraskin** [cloudfoundry/tps#11]
Hello, 

having kind of access log that will keep track of the requests coming to /v1/ endpoint would be helpful for the debugging purpose. 

We had an issue on production a couple of days ago where one of the cc_bridges was not able to send lrp stats back to CC. It took some time to identify the culprit, having such kind of log, would have helped to save much time. 

Would be great to hear some comments from you guys.

Thanks,

Vadim

**Comment by zrob** [comment]
hey @vvraskin 

We are currently working on removing the TPS Listener component from CloudFoundry.  Cloud Controller will instead call into BBS directly to get application information.  Due to this upcoming change we will not be adding anything to TPS Listener unless it is a security concern.

thanks 
@zrob
